---
- name: Install unattended upgrades package.
  package:
    name: unattended-upgrades
    state: present

- name: Copy unattended-upgrades configuration files in place.
  template:
    src: "{{ item.split('/') | last }}"
    dest: "/etc/apt/apt.conf.d/{{ item.split('/') | last | split('.') | first }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ security_apt_periodic_template }}"
    - "{{ security_unattenden_upgrade_template }}"
